################################################################
# begin oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="rjohnst"

plugins=(
    dirhistory
    zsh-history-substring-search
)

source $ZSH/oh-my-zsh.sh

bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down


# end oh-my-zsh
################################################################
