################################################################
# begin oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
export DISABLE_UPDATE_PROMPT=true

ZSH_THEME="rjohnst"

plugins=(
    dirhistory
    fzf-tab
    z
    zsh-autosuggestions
    zsh-history-substring-search
)

source $ZSH/oh-my-zsh.sh

bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down

# end oh-my-zsh
################################################################
